apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: kafka-redis-status-service
  environment: dev

namespace: kafka-redis-status 